application: zenwarchi
version: 2
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

libraries:
- name: jinja2
  version: "2.6"

- name: webapp2
  version: "2.5.2"

- name: webob
  version: "1.2.3"

- name: markupsafe
  version: "0.15"

- name: setuptools
  version: "0.6c11"

handlers:
- url: /
  script: convention.app

- url: /robots.txt
  static_files: web/static/robots.txt
  upload: web/static/robots.txt

- url: /favicon
  static_files: web/static/img/favicon.ico
  upload: web/static/img/favicon.ico

- url: /(.*)static(.*)
  static_files: web/\1static\2
  upload: web/.*static.*

- url: /(.*)static(.*)
  static_files: web/\1static\2
  upload: web/.*static.*

- url: /_ah/warmup
  script: warmup.app

- url: /.*
  script: convention.app

